# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: git@github.com:One2r/commit-msg-hook.git
    rev: '2512d941c6cf79dabcb7a3845d9f082406cd2db7'
    hooks:
      - id: commit-msg
        stages: [commit-msg]
